# Generated by Django 3.1 on 2020-10-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='classcode',
            field=models.CharField(default='sec_f', max_length=10),
            preserve_default=False,
        ),
    ]
