# Generated by Django 3.1 on 2020-10-16 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_discussion_classcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='classcode',
            new_name='classid',
        ),
    ]
