# Generated by Django 3.1 on 2020-10-16 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201016_2031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='classid',
            new_name='classcode',
        ),
    ]
