# Generated by Django 3.1 on 2020-10-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201016_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='poster',
            field=models.CharField(default='aa', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
